name: GitHub Snake

on:
  push:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: AlexCajeFelix  # Seu nome de usuário
          entryPoint: "main"  # Ou o nome do branch que você deseja monitorar
          args: "-o output/github-contribution-grid-snake.svg"  # Caminho do arquivo de saída
